### ISSUE TITLE
Bug columns not wanted in dangling lines dataframe

### ISSUE THREAD

**Issue by EtienneLt** [powsybl/pypowsybl#216] opened 2021-08-23 09:01 UTC
* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

after running a loadflow when asking for dangling lines there are 2 not wanted columns V and angle.
It happens only on dangling line network test.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```python
n = self.create_dangling_lines_network()
pp.loadflow.run_ac(n)
print('')
print(tabulate.tabulate(n.get_dangling_lines(), n.get_dangling_lines().columns))
```

* **What is the expected behavior?**

remove this 2 columns

**Comment by sylvlecl** [comment] 2021-09-17 09:32
Those 2 columns probably correspond to "properties" of the dangling lines. The properties of network elements are inserted after other columns.

To be confirmed though: I don't know exactly what processing is inserting those properties (is it open-loadflow ?), but it will probably not be considered a bug.

**Comment by geofjamg** [comment] 2021-09-17 09:49
> Those 2 columns probably correspond to "properties" of the dangling lines. The properties of network elements are inserted after other columns.
> 
> To be confirmed though: I don't know exactly what processing is inserting those properties (is it open-loadflow ?), but it will probably not be considered a bug.

If it is "v" and "angle", yes it comes from OLF to store voltage of dangling line middle bus to ba able to restart fully from previous state (same for 3 windings transfo middle bus)

**Comment by sylvlecl** [comment] 2021-09-17 14:02
OK!
I close the issue since it's the expected behaviour from pypowsybl point of view.

**Closed as completed by sylvlecl** 2021-09-17 14:02 UTC
Labels: bug
